const MAX_LIMIT: i32 = 100;
const IS_DEBUG: bool = true;

extern "C" def printf(fmt: *u8, ...) -> i32;

def main() -> i32 {
    let x: i32 = MAX_LIMIT;
    if IS_DEBUG {
        printf("Limit is %d\n" as *u8, x);
    }
    return 0;
}
