global_asm("
.global __rest_swapcontext
__rest_swapcontext:
    pushq %rbp
    pushq %rbx
    pushq %r12
    pushq %r13
    pushq %r14
    pushq %r15
    movq %rsp, (%rdi)
    movq %rsi, %rsp
    popq %r15
    popq %r14
    popq %r13
    popq %r12
    popq %rbx
    popq %rbp
    ret

.global __fiber_entry_asm
__fiber_entry_asm:
    // When __rest_swapcontext returns to a new fiber, 
    // it will pop the address of this function and jump here.
    // At this point, R12 = sched, R13 = func_id
.global __rest_fiber_entry
__rest_fiber_entry:
    sub $8, %rsp
    movq %r12, %rdi
    movq %r13, %rsi
    call fiber_router
    movq %r12, %rdi
    call fiber_exit
    // fiber_exit never returns (it swaps context back to the scheduler).
    ud2

.global get_fiber_entry_addr
get_fiber_entry_addr:
    lea __fiber_entry_asm(%rip), %rax
    ret
");

extern "C" def __rest_swapcontext(old_sp: **u8, new_sp: *u8);
extern "C" def __fiber_entry_asm();
extern "C" def get_fiber_entry_addr() -> i64;
